
#include <stddef.h>

char *level5[] = {
"82",
"168",
"17",
"5",
"25",
"164  84   0",
"  0 164 164",
"164   0   0",
"  0 164 164",
" 84 164  84",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                       *                                                          ",
"                                                                                  ",
"ppppppppppqr                          pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppqr                        pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppqr                      pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppqr                    pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppqr                  pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                  pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                  pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                  pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                  pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp      `a          pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp      bc          pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppuv                   wxppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppuv[                     \\wxppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppuvXYZ                     ]^_wpppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                              pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                              pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                              pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                def           pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                ghi   `a `a   pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppp                jkl   bc bc   pppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp#######pppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp   *   pppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppuv           pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppuv             pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppuv               pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppuv                 pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppuv                   pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp                               pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp                               pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp                               pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp                               pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp                               pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp                           UVWspppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp            `a             Tstppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp            bc            stppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp#########pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp    *    pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp         wxpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp           wxpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp             wxpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp               wxpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppp                 wxpppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppqr                 wxpppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppqr                 wxpppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppqr                 wxpppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppqr                 pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppqr               pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppp               pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppp               pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppp               pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppp                    pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppp                    pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppp                    pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppp                    pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppp                    pppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppp                   #    wxpppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppp                   #     \\wxpppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppqrPQR              #     ]^_wxpppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppqrS  `a `a       #          pppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppqr bc bc       #          pppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp#####  *       pppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp               pppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp               pppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp                       pppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp                       pppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp                     1Npppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppp                      Opppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppqrPQR                  pppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppqrS   `a `a          pppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppqr  bc bc          pppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppIIIIIIIpppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppKKKKKKKpppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp       wxpppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp#########wxpppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp          \\wxpppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp          ]^_wxpppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp    *          pppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppp1L              pppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppM              pppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp               pppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp               pppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp               pppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp              spppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppp     m0     stppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppqr   12   stppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppqr 34 stppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
NULL };
