
#include <stddef.h>

char *level6[] = {
"82",
"215",
"17",
"5",
"25",
"168   0 168",
"168  84  84",
" 84 164  84",
"  0 168 168",
"164   0   0",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                 *                                                                ",
"                                                                                  ",
"pppppppp                                                  stpppppppppppppppppppppp",
"pppppppp                                                stpppppppppppppppppppppppp",
"pppppppp                                              stpppppppppppppppppppppppppp",
"pppppppp                                            stpppppppppppppppppppppppppppp",
"pppppppp                                          stpppppppppppppppppppppppppppppp",
"pppppppp                                        stpppppppppppppppppppppppppppppppp",
"pppppppp                                      stpppppppppppppppppppppppppppppppppp",
"pppppppp                                    stpppppppppppppppppppppppppppppppppppp",
"pppppppp                                  stpppppppppppppppppppppppppppppppppppppp",
"pppppppp                                stpppppppppppppppppppppppppppppppppppppppp",
"pppppppp                              stpppppppppppppppppppppppppppppppppppppppppp",
"pppppppp                              pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppp                              pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppp                              pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppp                              pppppppppppppppppppppppppppppppppppppppppppp",
"pppppppp                              pppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppqr                  wxpppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppqr                  wxpppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppqr                  wxpppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppqr                  wxpppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppqr                 \\wxpppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppqr               ]^_wxpppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppqr                  wxpppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppqr                  wxpppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppqr                  wxpppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppqr                  wxpppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppqr                  wxpppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppqr                  wxpppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppqr                  wxpppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppqr                  wxpppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppqr                  pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppqr                pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppqr              pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppqr            pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppqr          pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppqr        pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppq       pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp       pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp#######pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppuv                wxpppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppuv[                   wxpppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppuvXYZ                    \\wxpppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp                         ]^_wxpppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp        *                     wxpppppp",
"pppppppppppppppppppppppppppppppppppppppppppp                                pppppp",
"pppppppppppppppppppppppppppppppppppppppppppp                                pppppp",
"pppppppppppppppppppppppppppppppppppppppppppp                                pppppp",
"pppppppppppppppppppppppppppppppppppppppppppp                     `a         pppppp",
"pppppppppppppppppppppppppppppppppppppppppppp                     bc         pppppp",
"pppppppppppppppppppppppppppppppppppppppppppp                  stpppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp                stpppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp           UVWstpppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp           Tstpppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp          stpppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp        stpppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp      stpppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp######pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp      wxpppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp   *    wxpppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp          wxpppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp           \\wxpppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp           ]^_wppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp               ppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp               ppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp               ppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp               ppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp           UVWsppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp           Tstpppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp          stpppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp          pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp          pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp          pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp          pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppp          pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp                  pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp                  pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp                  pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp                  pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp          `a      pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp          bc      pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp       ppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp       ppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp#######ppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp       ppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp       ppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp   *   ppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp       ppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppu       ppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppuv        ppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppuv[         ppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppvXYZ         wxppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppp               wxppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppp                \\wxppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppp                ]^_wxppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppo                    wxppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppno                    wxppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppno                    wxppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppno                    wxppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppno                    wxppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppno                ### wxppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppno            ###     wxppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppno        ###  *      wpppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppno    ###            pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppno ##            1Npppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppno              Opppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppno#############pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppno           pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppno         pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppBpppppppApppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppBpppppppApppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppEpppppppDpppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppEpppppppDpppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppuv         pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppuv           pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppuv[            pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppXYZ            pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp               pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp               pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp               pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppp1L              pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppM              pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp               pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp               pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppu               pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppuv[               pppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppuvXYZ               pppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp                   spppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp                 stppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp               stppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp          UVWstppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp          Tstppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp         stppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp       stppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp      tppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp      pppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp  m0  pppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp  12  pppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppp  34  pppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp pppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp pppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp         pppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp         pppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp         pppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp    def  pppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp    ghi  pppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppppppp    jkl  pppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
NULL };
