
#include <stddef.h>

char *level4[] = {
"82",
"128",
"17",
"5",
"25",
"  0  84 164",
"164   0   0",
"  0 164   0",
"  0 164 164",
"164  84  84",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                       *                                                          ",
"                                                                                  ",
"pppppppppppqr                       pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppqr                     pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppqr                   pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppqr                 pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppqr               pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppp       pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppuv       pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppuv         pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppuv[          pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppuvXYZ          pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppuv               pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppuv                 pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppuv                   pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppuv                     pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppuv                       pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppp                         pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppp                         pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppp                         pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppprPQR                     pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppqrS                     pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppqr      pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppp######pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppuv   *  pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppuv[       wxpppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppuvXYZ         wxpppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppuv               \\wxpppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppuv                 ]^_wxpppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppp                        wxpppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppp                          wxpppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppp                                     #          pppppppppppppppppppppppppppp",
"pppppp                                     #          pppppppppppppppppppppppppppp",
"pppppp                                     #          pppppppppppppppppppppppppppp",
"pppppp      def                            #    *     pppppppppppppppppppppppppppp",
"pppppp      ghi                            #          pppppppppppppppppppppppppppp",
"pppppp      jkl                            #          pppppppppppppppppppppppppppp",
"ppppppppppppppppppqr                       #          pppppppppppppppppppppppppppp",
"ppppppppppppppppppppqrPQR                  #          pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppqrS                  #        1Npppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppqr              `a #         Opppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppqr            bc #          pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppp         pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppp         pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppHppppppGpppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppHppppppGpppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppppHppppppGpppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppp         pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppp         pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppppppppppppppppp         pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppuv         pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppuv#        1Npppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppuv  #         Opppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppuv    #          pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppuv[     ###########pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppuvXYZ                pppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppuv          *          pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp                       pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp                       pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp                       pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp                       pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp                       pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp                       pppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp                     stpppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp                UVWstpppppppppppppppppppppppppppppp",
"ppppppppppppppppppppppppppppppp                Tstpppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppqr             stpppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppqr         stpppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppq}     ztpppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp|     yppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp|  m0 yppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp|  12 yppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppp|  34 yppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
NULL };
