
#include <stddef.h>

char *level2[] = {
"82",
"90",
"17",
"5",
"25",
" 24 211  24",
" 90  81 255",
"189  24  33",
" 49 231 198",
"189  65   0",
"         *                                                                        ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"  def                                   stpppppppppppppppppppppppppppppqr         ",
"  ghi                                 stpppppppppppppppppppppppppppppppppqr       ",
"  jkl                               stpppppppppppppppppppppppppppppppppppppqr     ",
"pppppppqr                         stpppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppqr                     stpppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppqr                 stpppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppqr             stpppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppqr           pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppqr         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp#########pppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppp         xppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppppu          wxppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppppuv            \\wxppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppppuv              ]^_wxppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppuv                     wpppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppuv[       *               pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppuvXYZ                       pppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppv                            pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppp                             pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppp                             pppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppp                           stpppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppr                        stpppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppqr      m0            stpppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppqr    12    `a    stpppppppppppppppppppppppppppppppppppppppppppppppppppp",
"ppppppppppppqr  34    bc  stpppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
NULL };
